// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fetchr/v1/fetchr.proto

package fetchrv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FetchrService_ResolveChannel_FullMethodName    = "/fetchr.v1.FetchrService/ResolveChannel"
	FetchrService_FetchChannel_FullMethodName      = "/fetchr.v1.FetchrService/FetchChannel"
	FetchrService_FetchRecentVideos_FullMethodName = "/fetchr.v1.FetchrService/FetchRecentVideos"
	FetchrService_CheckNewUploads_FullMethodName   = "/fetchr.v1.FetchrService/CheckNewUploads"
)

// FetchrServiceClient is the client API for FetchrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FetchrService is the sole caller of upstream platform APIs (YouTube today,
// others later). Every other service resolves and fetches channel/video data
// through this service rather than talking to the platform directly.
type FetchrServiceClient interface {
	// ResolveChannel canonicalises a platform handle to a channel id and
	// upserts it into the global channel registry, so that repeated
	// registrations of the same competitor by different users dedupe onto one
	// row.
	ResolveChannel(ctx context.Context, in *ResolveChannelRequest, opts ...grpc.CallOption) (*ResolveChannelResponse, error)
	// FetchChannel refreshes and returns a channel's metadata.
	FetchChannel(ctx context.Context, in *FetchChannelRequest, opts ...grpc.CallOption) (*FetchChannelResponse, error)
	// FetchRecentVideos returns the channel's most recent videos as full
	// VideoPackets. Used with a small limit for a user's own channel during
	// onboarding.
	FetchRecentVideos(ctx context.Context, in *FetchRecentVideosRequest, opts ...grpc.CallOption) (*FetchRecentVideosResponse, error)
	// CheckNewUploads compares the channel's latest upload against
	// since_published_at and returns any videos published after it.
	CheckNewUploads(ctx context.Context, in *CheckNewUploadsRequest, opts ...grpc.CallOption) (*CheckNewUploadsResponse, error)
}

type fetchrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFetchrServiceClient(cc grpc.ClientConnInterface) FetchrServiceClient {
	return &fetchrServiceClient{cc}
}

func (c *fetchrServiceClient) ResolveChannel(ctx context.Context, in *ResolveChannelRequest, opts ...grpc.CallOption) (*ResolveChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveChannelResponse)
	err := c.cc.Invoke(ctx, FetchrService_ResolveChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchrServiceClient) FetchChannel(ctx context.Context, in *FetchChannelRequest, opts ...grpc.CallOption) (*FetchChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchChannelResponse)
	err := c.cc.Invoke(ctx, FetchrService_FetchChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchrServiceClient) FetchRecentVideos(ctx context.Context, in *FetchRecentVideosRequest, opts ...grpc.CallOption) (*FetchRecentVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchRecentVideosResponse)
	err := c.cc.Invoke(ctx, FetchrService_FetchRecentVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchrServiceClient) CheckNewUploads(ctx context.Context, in *CheckNewUploadsRequest, opts ...grpc.CallOption) (*CheckNewUploadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNewUploadsResponse)
	err := c.cc.Invoke(ctx, FetchrService_CheckNewUploads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FetchrServiceServer is the server API for FetchrService service.
// All implementations must embed UnimplementedFetchrServiceServer
// for forward compatibility.
//
// FetchrService is the sole caller of upstream platform APIs (YouTube today,
// others later). Every other service resolves and fetches channel/video data
// through this service rather than talking to the platform directly.
type FetchrServiceServer interface {
	// ResolveChannel canonicalises a platform handle to a channel id and
	// upserts it into the global channel registry, so that repeated
	// registrations of the same competitor by different users dedupe onto one
	// row.
	ResolveChannel(context.Context, *ResolveChannelRequest) (*ResolveChannelResponse, error)
	// FetchChannel refreshes and returns a channel's metadata.
	FetchChannel(context.Context, *FetchChannelRequest) (*FetchChannelResponse, error)
	// FetchRecentVideos returns the channel's most recent videos as full
	// VideoPackets. Used with a small limit for a user's own channel during
	// onboarding.
	FetchRecentVideos(context.Context, *FetchRecentVideosRequest) (*FetchRecentVideosResponse, error)
	// CheckNewUploads compares the channel's latest upload against
	// since_published_at and returns any videos published after it.
	CheckNewUploads(context.Context, *CheckNewUploadsRequest) (*CheckNewUploadsResponse, error)
	mustEmbedUnimplementedFetchrServiceServer()
}

// UnimplementedFetchrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFetchrServiceServer struct{}

func (UnimplementedFetchrServiceServer) ResolveChannel(context.Context, *ResolveChannelRequest) (*ResolveChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveChannel not implemented")
}
func (UnimplementedFetchrServiceServer) FetchChannel(context.Context, *FetchChannelRequest) (*FetchChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchChannel not implemented")
}
func (UnimplementedFetchrServiceServer) FetchRecentVideos(context.Context, *FetchRecentVideosRequest) (*FetchRecentVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRecentVideos not implemented")
}
func (UnimplementedFetchrServiceServer) CheckNewUploads(context.Context, *CheckNewUploadsRequest) (*CheckNewUploadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNewUploads not implemented")
}
func (UnimplementedFetchrServiceServer) mustEmbedUnimplementedFetchrServiceServer() {}
func (UnimplementedFetchrServiceServer) testEmbeddedByValue()                       {}

// UnsafeFetchrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FetchrServiceServer will
// result in compilation errors.
type UnsafeFetchrServiceServer interface {
	mustEmbedUnimplementedFetchrServiceServer()
}

func RegisterFetchrServiceServer(s grpc.ServiceRegistrar, srv FetchrServiceServer) {
	// If the following call pancis, it indicates UnimplementedFetchrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FetchrService_ServiceDesc, srv)
}

func _FetchrService_ResolveChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchrServiceServer).ResolveChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FetchrService_ResolveChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchrServiceServer).ResolveChannel(ctx, req.(*ResolveChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchrService_FetchChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchrServiceServer).FetchChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FetchrService_FetchChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchrServiceServer).FetchChannel(ctx, req.(*FetchChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchrService_FetchRecentVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRecentVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchrServiceServer).FetchRecentVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FetchrService_FetchRecentVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchrServiceServer).FetchRecentVideos(ctx, req.(*FetchRecentVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchrService_CheckNewUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNewUploadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchrServiceServer).CheckNewUploads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FetchrService_CheckNewUploads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchrServiceServer).CheckNewUploads(ctx, req.(*CheckNewUploadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FetchrService_ServiceDesc is the grpc.ServiceDesc for FetchrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FetchrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fetchr.v1.FetchrService",
	HandlerType: (*FetchrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveChannel",
			Handler:    _FetchrService_ResolveChannel_Handler,
		},
		{
			MethodName: "FetchChannel",
			Handler:    _FetchrService_FetchChannel_Handler,
		},
		{
			MethodName: "FetchRecentVideos",
			Handler:    _FetchrService_FetchRecentVideos_Handler,
		},
		{
			MethodName: "CheckNewUploads",
			Handler:    _FetchrService_CheckNewUploads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fetchr/v1/fetchr.proto",
}
