// waverider-protos

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: competitive_intel/v1/comp_intel.proto

package competitiveintelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompetitiveIntelService_AddCompetitor_FullMethodName            = "/competitive_intel.v1.CompetitiveIntelService/AddCompetitor"
	CompetitiveIntelService_GetCompetitors_FullMethodName           = "/competitive_intel.v1.CompetitiveIntelService/GetCompetitors"
	CompetitiveIntelService_GetAlerts_FullMethodName                = "/competitive_intel.v1.CompetitiveIntelService/GetAlerts"
	CompetitiveIntelService_AnalyzeCompetitorContent_FullMethodName = "/competitive_intel.v1.CompetitiveIntelService/AnalyzeCompetitorContent"
	CompetitiveIntelService_RemoveCompetitor_FullMethodName         = "/competitive_intel.v1.CompetitiveIntelService/RemoveCompetitor"
)

// CompetitiveIntelServiceClient is the client API for CompetitiveIntelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CompetitiveIntelService provides competitor tracking and content analysis
type CompetitiveIntelServiceClient interface {
	// AddCompetitor starts tracking a competitor
	AddCompetitor(ctx context.Context, in *AddCompetitorRequest, opts ...grpc.CallOption) (*AddCompetitorResponse, error)
	// GetCompetitors retrieves all tracked competitors for a user
	GetCompetitors(ctx context.Context, in *GetCompetitorsRequest, opts ...grpc.CallOption) (*GetCompetitorsResponse, error)
	// GetAlerts retrieves "Ride the Wave" alerts for recent competitor uploads
	GetAlerts(ctx context.Context, in *GetAlertsRequest, opts ...grpc.CallOption) (*GetAlertsResponse, error)
	// AnalyzeCompetitorContent generates content suggestions based on competitor's latest video
	AnalyzeCompetitorContent(ctx context.Context, in *AnalyzeContentRequest, opts ...grpc.CallOption) (*AnalyzeContentResponse, error)
	// RemoveCompetitor stops tracking a competitor
	RemoveCompetitor(ctx context.Context, in *RemoveCompetitorRequest, opts ...grpc.CallOption) (*RemoveCompetitorResponse, error)
}

type competitiveIntelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompetitiveIntelServiceClient(cc grpc.ClientConnInterface) CompetitiveIntelServiceClient {
	return &competitiveIntelServiceClient{cc}
}

func (c *competitiveIntelServiceClient) AddCompetitor(ctx context.Context, in *AddCompetitorRequest, opts ...grpc.CallOption) (*AddCompetitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCompetitorResponse)
	err := c.cc.Invoke(ctx, CompetitiveIntelService_AddCompetitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitiveIntelServiceClient) GetCompetitors(ctx context.Context, in *GetCompetitorsRequest, opts ...grpc.CallOption) (*GetCompetitorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompetitorsResponse)
	err := c.cc.Invoke(ctx, CompetitiveIntelService_GetCompetitors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitiveIntelServiceClient) GetAlerts(ctx context.Context, in *GetAlertsRequest, opts ...grpc.CallOption) (*GetAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertsResponse)
	err := c.cc.Invoke(ctx, CompetitiveIntelService_GetAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitiveIntelServiceClient) AnalyzeCompetitorContent(ctx context.Context, in *AnalyzeContentRequest, opts ...grpc.CallOption) (*AnalyzeContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeContentResponse)
	err := c.cc.Invoke(ctx, CompetitiveIntelService_AnalyzeCompetitorContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *competitiveIntelServiceClient) RemoveCompetitor(ctx context.Context, in *RemoveCompetitorRequest, opts ...grpc.CallOption) (*RemoveCompetitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveCompetitorResponse)
	err := c.cc.Invoke(ctx, CompetitiveIntelService_RemoveCompetitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompetitiveIntelServiceServer is the server API for CompetitiveIntelService service.
// All implementations must embed UnimplementedCompetitiveIntelServiceServer
// for forward compatibility.
//
// CompetitiveIntelService provides competitor tracking and content analysis
type CompetitiveIntelServiceServer interface {
	// AddCompetitor starts tracking a competitor
	AddCompetitor(context.Context, *AddCompetitorRequest) (*AddCompetitorResponse, error)
	// GetCompetitors retrieves all tracked competitors for a user
	GetCompetitors(context.Context, *GetCompetitorsRequest) (*GetCompetitorsResponse, error)
	// GetAlerts retrieves "Ride the Wave" alerts for recent competitor uploads
	GetAlerts(context.Context, *GetAlertsRequest) (*GetAlertsResponse, error)
	// AnalyzeCompetitorContent generates content suggestions based on competitor's latest video
	AnalyzeCompetitorContent(context.Context, *AnalyzeContentRequest) (*AnalyzeContentResponse, error)
	// RemoveCompetitor stops tracking a competitor
	RemoveCompetitor(context.Context, *RemoveCompetitorRequest) (*RemoveCompetitorResponse, error)
	mustEmbedUnimplementedCompetitiveIntelServiceServer()
}

// UnimplementedCompetitiveIntelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompetitiveIntelServiceServer struct{}

func (UnimplementedCompetitiveIntelServiceServer) AddCompetitor(context.Context, *AddCompetitorRequest) (*AddCompetitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCompetitor not implemented")
}
func (UnimplementedCompetitiveIntelServiceServer) GetCompetitors(context.Context, *GetCompetitorsRequest) (*GetCompetitorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompetitors not implemented")
}
func (UnimplementedCompetitiveIntelServiceServer) GetAlerts(context.Context, *GetAlertsRequest) (*GetAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlerts not implemented")
}
func (UnimplementedCompetitiveIntelServiceServer) AnalyzeCompetitorContent(context.Context, *AnalyzeContentRequest) (*AnalyzeContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeCompetitorContent not implemented")
}
func (UnimplementedCompetitiveIntelServiceServer) RemoveCompetitor(context.Context, *RemoveCompetitorRequest) (*RemoveCompetitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCompetitor not implemented")
}
func (UnimplementedCompetitiveIntelServiceServer) mustEmbedUnimplementedCompetitiveIntelServiceServer() {
}
func (UnimplementedCompetitiveIntelServiceServer) testEmbeddedByValue() {}

// UnsafeCompetitiveIntelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompetitiveIntelServiceServer will
// result in compilation errors.
type UnsafeCompetitiveIntelServiceServer interface {
	mustEmbedUnimplementedCompetitiveIntelServiceServer()
}

func RegisterCompetitiveIntelServiceServer(s grpc.ServiceRegistrar, srv CompetitiveIntelServiceServer) {
	// If the following call pancis, it indicates UnimplementedCompetitiveIntelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompetitiveIntelService_ServiceDesc, srv)
}

func _CompetitiveIntelService_AddCompetitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCompetitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitiveIntelServiceServer).AddCompetitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitiveIntelService_AddCompetitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitiveIntelServiceServer).AddCompetitor(ctx, req.(*AddCompetitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitiveIntelService_GetCompetitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompetitorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitiveIntelServiceServer).GetCompetitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitiveIntelService_GetCompetitors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitiveIntelServiceServer).GetCompetitors(ctx, req.(*GetCompetitorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitiveIntelService_GetAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitiveIntelServiceServer).GetAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitiveIntelService_GetAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitiveIntelServiceServer).GetAlerts(ctx, req.(*GetAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitiveIntelService_AnalyzeCompetitorContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitiveIntelServiceServer).AnalyzeCompetitorContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitiveIntelService_AnalyzeCompetitorContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitiveIntelServiceServer).AnalyzeCompetitorContent(ctx, req.(*AnalyzeContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompetitiveIntelService_RemoveCompetitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCompetitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompetitiveIntelServiceServer).RemoveCompetitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompetitiveIntelService_RemoveCompetitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompetitiveIntelServiceServer).RemoveCompetitor(ctx, req.(*RemoveCompetitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompetitiveIntelService_ServiceDesc is the grpc.ServiceDesc for CompetitiveIntelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompetitiveIntelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "competitive_intel.v1.CompetitiveIntelService",
	HandlerType: (*CompetitiveIntelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCompetitor",
			Handler:    _CompetitiveIntelService_AddCompetitor_Handler,
		},
		{
			MethodName: "GetCompetitors",
			Handler:    _CompetitiveIntelService_GetCompetitors_Handler,
		},
		{
			MethodName: "GetAlerts",
			Handler:    _CompetitiveIntelService_GetAlerts_Handler,
		},
		{
			MethodName: "AnalyzeCompetitorContent",
			Handler:    _CompetitiveIntelService_AnalyzeCompetitorContent_Handler,
		},
		{
			MethodName: "RemoveCompetitor",
			Handler:    _CompetitiveIntelService_RemoveCompetitor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "competitive_intel/v1/comp_intel.proto",
}
