// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: contentengine/v1/content_engine.proto

package contentenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentEngineService_CreateContentRequest_FullMethodName              = "/contentengine.v1.ContentEngineService/CreateContentRequest"
	ContentEngineService_GetContentRequest_FullMethodName                 = "/contentengine.v1.ContentEngineService/GetContentRequest"
	ContentEngineService_ListContentRequests_FullMethodName               = "/contentengine.v1.ContentEngineService/ListContentRequests"
	ContentEngineService_ApproveRecommendation_FullMethodName             = "/contentengine.v1.ContentEngineService/ApproveRecommendation"
	ContentEngineService_RegenerateRecommendations_FullMethodName         = "/contentengine.v1.ContentEngineService/RegenerateRecommendations"
	ContentEngineService_GetChannelVideoRecommendations_FullMethodName    = "/contentengine.v1.ContentEngineService/GetChannelVideoRecommendations"
	ContentEngineService_ApproveChannelVideoRecommendation_FullMethodName = "/contentengine.v1.ContentEngineService/ApproveChannelVideoRecommendation"
)

// ContentEngineServiceClient is the client API for ContentEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentEngineService turns some input (a competitor's video, a user's
// on-demand brief, trending tags, promo media) into content the user can
// post. Generation is two-stage and approval-gated: CreateContentRequest
// produces 3 short, disposable recommendations; ApproveRecommendation picks
// exactly one and generates the full script/description for it. Both RPCs
// return immediately — they persist-and-emit only, never call an LLM
// synchronously — so a caller never blocks on generation latency. The
// caller's user id is always taken from the bearer token, never from the
// request.
type ContentEngineServiceClient interface {
	CreateContentRequest(ctx context.Context, in *CreateContentRequestRequest, opts ...grpc.CallOption) (*ContentRequest, error)
	GetContentRequest(ctx context.Context, in *GetContentRequestRequest, opts ...grpc.CallOption) (*ContentRequest, error)
	ListContentRequests(ctx context.Context, in *ListContentRequestsRequest, opts ...grpc.CallOption) (*ListContentRequestsResponse, error)
	ApproveRecommendation(ctx context.Context, in *ApproveRecommendationRequest, opts ...grpc.CallOption) (*ContentRequest, error)
	RegenerateRecommendations(ctx context.Context, in *RegenerateRecommendationsRequest, opts ...grpc.CallOption) (*ContentRequest, error)
	// GetChannelVideoRecommendations / ApproveChannelVideoRecommendation are
	// the competitor-video path: the 3 recommendations for a given video are
	// generated exactly once (shared across every subscriber of that
	// channel), never keyed to a user, and never persona-flavored. A
	// subscriber approves one of the shared ideas to get their own
	// persona-flavored ContentRequest — same stage-2 generation
	// ApproveRecommendation's approval triggers, just entered from a shared
	// idea instead of a per-user CreateContentRequest.
	GetChannelVideoRecommendations(ctx context.Context, in *GetChannelVideoRecommendationsRequest, opts ...grpc.CallOption) (*ChannelVideoRecommendations, error)
	ApproveChannelVideoRecommendation(ctx context.Context, in *ApproveChannelVideoRecommendationRequest, opts ...grpc.CallOption) (*ContentRequest, error)
}

type contentEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentEngineServiceClient(cc grpc.ClientConnInterface) ContentEngineServiceClient {
	return &contentEngineServiceClient{cc}
}

func (c *contentEngineServiceClient) CreateContentRequest(ctx context.Context, in *CreateContentRequestRequest, opts ...grpc.CallOption) (*ContentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentRequest)
	err := c.cc.Invoke(ctx, ContentEngineService_CreateContentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) GetContentRequest(ctx context.Context, in *GetContentRequestRequest, opts ...grpc.CallOption) (*ContentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentRequest)
	err := c.cc.Invoke(ctx, ContentEngineService_GetContentRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) ListContentRequests(ctx context.Context, in *ListContentRequestsRequest, opts ...grpc.CallOption) (*ListContentRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContentRequestsResponse)
	err := c.cc.Invoke(ctx, ContentEngineService_ListContentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) ApproveRecommendation(ctx context.Context, in *ApproveRecommendationRequest, opts ...grpc.CallOption) (*ContentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentRequest)
	err := c.cc.Invoke(ctx, ContentEngineService_ApproveRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) RegenerateRecommendations(ctx context.Context, in *RegenerateRecommendationsRequest, opts ...grpc.CallOption) (*ContentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentRequest)
	err := c.cc.Invoke(ctx, ContentEngineService_RegenerateRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) GetChannelVideoRecommendations(ctx context.Context, in *GetChannelVideoRecommendationsRequest, opts ...grpc.CallOption) (*ChannelVideoRecommendations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelVideoRecommendations)
	err := c.cc.Invoke(ctx, ContentEngineService_GetChannelVideoRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentEngineServiceClient) ApproveChannelVideoRecommendation(ctx context.Context, in *ApproveChannelVideoRecommendationRequest, opts ...grpc.CallOption) (*ContentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentRequest)
	err := c.cc.Invoke(ctx, ContentEngineService_ApproveChannelVideoRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentEngineServiceServer is the server API for ContentEngineService service.
// All implementations must embed UnimplementedContentEngineServiceServer
// for forward compatibility.
//
// ContentEngineService turns some input (a competitor's video, a user's
// on-demand brief, trending tags, promo media) into content the user can
// post. Generation is two-stage and approval-gated: CreateContentRequest
// produces 3 short, disposable recommendations; ApproveRecommendation picks
// exactly one and generates the full script/description for it. Both RPCs
// return immediately — they persist-and-emit only, never call an LLM
// synchronously — so a caller never blocks on generation latency. The
// caller's user id is always taken from the bearer token, never from the
// request.
type ContentEngineServiceServer interface {
	CreateContentRequest(context.Context, *CreateContentRequestRequest) (*ContentRequest, error)
	GetContentRequest(context.Context, *GetContentRequestRequest) (*ContentRequest, error)
	ListContentRequests(context.Context, *ListContentRequestsRequest) (*ListContentRequestsResponse, error)
	ApproveRecommendation(context.Context, *ApproveRecommendationRequest) (*ContentRequest, error)
	RegenerateRecommendations(context.Context, *RegenerateRecommendationsRequest) (*ContentRequest, error)
	// GetChannelVideoRecommendations / ApproveChannelVideoRecommendation are
	// the competitor-video path: the 3 recommendations for a given video are
	// generated exactly once (shared across every subscriber of that
	// channel), never keyed to a user, and never persona-flavored. A
	// subscriber approves one of the shared ideas to get their own
	// persona-flavored ContentRequest — same stage-2 generation
	// ApproveRecommendation's approval triggers, just entered from a shared
	// idea instead of a per-user CreateContentRequest.
	GetChannelVideoRecommendations(context.Context, *GetChannelVideoRecommendationsRequest) (*ChannelVideoRecommendations, error)
	ApproveChannelVideoRecommendation(context.Context, *ApproveChannelVideoRecommendationRequest) (*ContentRequest, error)
	mustEmbedUnimplementedContentEngineServiceServer()
}

// UnimplementedContentEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentEngineServiceServer struct{}

func (UnimplementedContentEngineServiceServer) CreateContentRequest(context.Context, *CreateContentRequestRequest) (*ContentRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContentRequest not implemented")
}
func (UnimplementedContentEngineServiceServer) GetContentRequest(context.Context, *GetContentRequestRequest) (*ContentRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContentRequest not implemented")
}
func (UnimplementedContentEngineServiceServer) ListContentRequests(context.Context, *ListContentRequestsRequest) (*ListContentRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContentRequests not implemented")
}
func (UnimplementedContentEngineServiceServer) ApproveRecommendation(context.Context, *ApproveRecommendationRequest) (*ContentRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRecommendation not implemented")
}
func (UnimplementedContentEngineServiceServer) RegenerateRecommendations(context.Context, *RegenerateRecommendationsRequest) (*ContentRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateRecommendations not implemented")
}
func (UnimplementedContentEngineServiceServer) GetChannelVideoRecommendations(context.Context, *GetChannelVideoRecommendationsRequest) (*ChannelVideoRecommendations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelVideoRecommendations not implemented")
}
func (UnimplementedContentEngineServiceServer) ApproveChannelVideoRecommendation(context.Context, *ApproveChannelVideoRecommendationRequest) (*ContentRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveChannelVideoRecommendation not implemented")
}
func (UnimplementedContentEngineServiceServer) mustEmbedUnimplementedContentEngineServiceServer() {}
func (UnimplementedContentEngineServiceServer) testEmbeddedByValue()                              {}

// UnsafeContentEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentEngineServiceServer will
// result in compilation errors.
type UnsafeContentEngineServiceServer interface {
	mustEmbedUnimplementedContentEngineServiceServer()
}

func RegisterContentEngineServiceServer(s grpc.ServiceRegistrar, srv ContentEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedContentEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentEngineService_ServiceDesc, srv)
}

func _ContentEngineService_CreateContentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).CreateContentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_CreateContentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).CreateContentRequest(ctx, req.(*CreateContentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_GetContentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).GetContentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_GetContentRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).GetContentRequest(ctx, req.(*GetContentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_ListContentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContentRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).ListContentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_ListContentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).ListContentRequests(ctx, req.(*ListContentRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_ApproveRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).ApproveRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_ApproveRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).ApproveRecommendation(ctx, req.(*ApproveRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_RegenerateRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).RegenerateRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_RegenerateRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).RegenerateRecommendations(ctx, req.(*RegenerateRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_GetChannelVideoRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelVideoRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).GetChannelVideoRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_GetChannelVideoRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).GetChannelVideoRecommendations(ctx, req.(*GetChannelVideoRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentEngineService_ApproveChannelVideoRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveChannelVideoRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentEngineServiceServer).ApproveChannelVideoRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentEngineService_ApproveChannelVideoRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentEngineServiceServer).ApproveChannelVideoRecommendation(ctx, req.(*ApproveChannelVideoRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentEngineService_ServiceDesc is the grpc.ServiceDesc for ContentEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentengine.v1.ContentEngineService",
	HandlerType: (*ContentEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContentRequest",
			Handler:    _ContentEngineService_CreateContentRequest_Handler,
		},
		{
			MethodName: "GetContentRequest",
			Handler:    _ContentEngineService_GetContentRequest_Handler,
		},
		{
			MethodName: "ListContentRequests",
			Handler:    _ContentEngineService_ListContentRequests_Handler,
		},
		{
			MethodName: "ApproveRecommendation",
			Handler:    _ContentEngineService_ApproveRecommendation_Handler,
		},
		{
			MethodName: "RegenerateRecommendations",
			Handler:    _ContentEngineService_RegenerateRecommendations_Handler,
		},
		{
			MethodName: "GetChannelVideoRecommendations",
			Handler:    _ContentEngineService_GetChannelVideoRecommendations_Handler,
		},
		{
			MethodName: "ApproveChannelVideoRecommendation",
			Handler:    _ContentEngineService_ApproveChannelVideoRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentengine/v1/content_engine.proto",
}
